# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
telephone: 021 442 1800
description: >
  At the UCT Ear Clinic we specialize in BAHA implants, cochlear implants, congenital ear problems and congenital ear pathology just to name a few. We are based at Groote Schuur Hospital.
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
